# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test API
      run: go test -v ./api

    - name: Test APP
      run: go test -v ./app

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v3

    - name: Build API
      run: docker build ./api -t jvitoroc17/local:api

    - name: Build APP
      run: docker build ./app -t jvitoroc17/local:app

    - name: Push API
      run: docker push jvitoroc17/local:api

    - name: Push APP
      run: docker push jvitoroc17/local:app
