name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "staging" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  test:
    strategy:
      matrix:
        service: [app, api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test ${{ matrix.service }}
      run: go test -v ./${{ matrix.service }}

  lint:
    strategy:
      matrix:
        service: [app, api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: ${{ matrix.service }}
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.2
        working-directory: ${{ matrix.service }}

  build:
    strategy:
      matrix:
        service: [app, api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Set Tag
      id: tag
      run: echo "TAG=jvitoroc17/devops-tour-${{ matrix.service }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"

    - name: Build ${{ matrix.service }}
      run: docker build ./${{ matrix.service }} -t ${{ steps.tag.outputs.TAG }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      if: github.event_name != 'pull_request'

    - name: Push ${{ matrix.service }}
      run: docker push ${{ steps.tag.outputs.TAG }}
      if: github.event_name != 'pull_request'