name: Go

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test API
      run: go test -v ./api

    - name: Test APP
      run: go test -v ./app

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.2
        working-directory: api

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.2
        working-directory: app

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test API
      run: go test -v ./api

    - name: Test APP
      run: go test -v ./app

    - name: Build API
      run: docker build ./api

    - name: Build APP
      run: docker build ./app

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [test, lint, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build API
      run: docker build ./api -t jvitoroc17/local:api

    - name: Build APP
      run: docker build ./app -t jvitoroc17/local:app

    - name: Push API
      run: docker push jvitoroc17/local:api

    - name: Push APP
      run: docker push jvitoroc17/local:app

