name: Go

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:

  test:
    strategy:
      matrix:
        service: [app, api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test ${{ matrix.service }}
      run: go test -v ./${{ matrix.service }}

  lint:
    strategy:
      matrix:
        service: [app, api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.2
        working-directory: ${{ matrix.service }}

  build:
    strategy:
      matrix:
        service: [app, api]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build API
      run: docker build ./${{ matrix.service }}

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [test, lint, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build API
      run: docker build ./api -t jvitoroc17/local:api

    - name: Build APP
      run: docker build ./app -t jvitoroc17/local:app

    - name: Push API
      run: docker push jvitoroc17/local:api

    - name: Push APP
      run: docker push jvitoroc17/local:app

